dist: trusty
language: java
jdk:
- oraclejdk8
install:
- java -version && javac -version && mvn -version -B
before_script:
- mvn dependency:resolve-plugins -B
script:
- mvn clean install -B
after_success:
- mvn test -Dtest=PerformanceTest -DfailIfNoTests=false -DargLine="-DnumIters=25000"
cache:
  directories:
  - $HOME/.m2
before_install:
  - wget https://dl.dropboxusercontent.com/u/7897865/apache-maven-3.3.9.zip
  - unzip -qq apache-maven-3.3.9.zip
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$M2_HOME/bin:$PATH
