before_install:
- wget https://dl.dropboxusercontent.com/u/7897865/apache-maven-3.3.9.zip
- unzip -qq apache-maven-3.3.9.zip
- export M2_HOME=$PWD/apache-maven-3.3.9
- export PATH=$M2_HOME/bin:$PATH
- bash .travis/deploy-codesigning.sh
sudo: required
dist: trusty
language: java
jdk:
- oraclejdk8
install:
- java -version && javac -version && mvn -version -B
before_script:
- mvn dependency:resolve-plugins -B
script:
- mvn clean install -B
after_success:
- mvn test -Dtest=PerformanceTest -DfailIfNoTests=false -DargLine="-DnumIters=25000"
deploy:
  provider: script
  script: bash .travis/deploy.sh
  skip_cleanup: true
cache:
  directories:
  - $HOME/.m2
dist: trusty
install:
- java -version && javac -version && mvn -version -B
jdk:
- oraclejdk8
language: java
notifications:
  email: false
  slack:
    rooms: flakycov:U2MeVOPjdi4up1U793ubeIUZ
    template:
    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}
    - 'dashbot: %{repository_name} %{build_id}'
script:
- mvn clean install -B
